auto: --auto
permalink: /:categories/:title
exclude: [ notes ]

_author: John Crandall &amp; Jason Gregori
_basepath: /podcast
_keywords: jason gregori, john crandall
_name: The Weekly Once-a-Week
_description_itunes: A podcast hosted by John Crandall &amp; Jason Gregori
_url: http://jasongregori.github.com/podcast
_taglines:
  - Jason and John beat each other up ... with friendship
  - Your going back in time ... to the future!
  - Jason, John, and the website they done built.
  - Nerdburgers!