auto: --auto
permalink: /:categories/:title
exclude: [ notes ]

_author: John Crandall &amp; Jason Gregori
_basepath: /podcast
_keywords: jason gregori, john crandall
_name: The Weekly Once-a-Week
_description_web: a podcast
_description_itunes: A podcast hosted by John Crandall &amp; Jason Gregori
_url: http://jasongregori.github.com/podcast