auto: --auto
permalink: /:categories/:title
exclude: [ notes, CNAME ]

_author: John Crandall &amp; Jason Gregori
_basepath: ""
_keywords: jason gregori, john crandall
_name: The Weekly Once-a-Week
_email: weeklyonceaweek@gmail.com
_itunes_link: http://itunes.apple.com/us/podcast/the-weekly-once-a-week/id524311501
_description_itunes: A podcast hosted by John Crandall &amp; Jason Gregori
_description_website: A podcast hosted by John Crandall &amp; Jason Gregori
_url: http://weeklyonceaweek.com
_taglines:
  - Jason and John beat each other up ... with friendship
  - You're going back in time ... to the future!
  - Jason, John, and the website they done built.
  - Nerdburgers!
  - It's moderately amusing!