auto: --auto
permalink: /:categories/:title
exclude: [ notes ]

_author: John Crandall &amp; Jason Gregori
_basepath: /john-and-jasons-podcast
_name: John and Jason's Podcast
_description_web: a podcast
_description_itunes: A podcast hosted by John Crandall &amp; Jason Gregori
_url: http://jasongregori.github.com/john-and-jasons-podcast